name: beets
channels:
  - conda-forge
dependencies:
  - pip:
      - beetcamp
      - python3-discogs-client
      - pylast
  - beets
  - pyacoustid
  - requests
  - pip
variables:
  BEETSDIR: ~/p/beets
